# Generated by Django 3.2.11 on 2022-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220724_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=15000)),
                ('name', models.CharField(max_length=111)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=5000)),
                ('state', models.CharField(max_length=111)),
                ('zip_code', models.CharField(max_length=500)),
            ],
        ),
    ]
